PUT http://localhost:8080/events/1
Content-Type: application/json

{
    "name": "Updated Test event",
    "description": "Updated A test event",
    "location": "UpdATED A test location",
    "dateTime": "2025-01-01T15:30:00.000Z"
}
